name: CodeQL analysis
description: 'Analyze code'
strategy:
  fail-fast: false
  matrix:
    language: [ 'csharp', 'javascript' ]
runs:
  using: "composite"
  steps:
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
