name: Build and deploy API
on:
  push:
    paths:
      - src/API/**
    branches:
      - master

env:
  WORKING_DIRECTORY: './src/API/'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301'
        include-prerelease: true
    - name: Build with dotnet
      run: dotnet build ${{ env.WORKING_DIRECTORY }}/RegioneLombardia.API/RegioneLombardia.API.csproj --configuration Release
    - name: dotnet publish
      run: dotnet publish ${{ env.WORKING_DIRECTORY }}/RegioneLombardia.API/RegioneLombardia.API.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: application
        path: ${{env.DOTNET_ROOT}}/myapp

  security:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: application
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: 'csharp'
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  deploy:
    runs-on: windows-latest
    needs: security
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: application
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'regionelombardia-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_81bc1cfc34234f7cad1301079ab15be4 }}
        package: .
        
  test:
    runs-on: ubuntu-18.04
    needs: [deploy]
    steps:
    - uses: actions/checkout@v2

    - name: Run local k6 test
      uses: k6io/action@v0.1
      with:
        filename: src/LoadTests/script.js
        flags: --env API_BASEURL=regionelombardia-api.azurewebsites.net/ --env API_PROTOCOL=https 
