name: Build and deploy API
on:
  push:
    paths:
      - src/API/**
    branches:
      - main

env:
  WORKING_DIRECTORY: './src/API/'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301'
        include-prerelease: true
    - name: Build with dotnet
      run: dotnet build ${{ env.WORKING_DIRECTORY }}/RegioneLombardia.API/RegioneLombardia.API.csproj --configuration Release
    - name: dotnet publish
      run: dotnet publish ${{ env.WORKING_DIRECTORY }}/RegioneLombardia.API/RegioneLombardia.API.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: .net-app
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'regionelombardia-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_097ce565b14f4d90aeb2b8226c26bc9d }}
        package: .
        
  test:
    runs-on: ubuntu-18.04
    needs: [deploy]
    steps:
    - uses: actions/checkout@v2

    - name: Run local k6 test
      uses: k6io/action@v0.1
      with:
        filename: src/LoadTests/script.js
        flags: --env API_BASEURL=regionelombardia-api.azurewebsites.net/ --env API_PROTOCOL=https 
