name: Build and deploy Web

on:
  push:
    paths:
      - src/Website/**
    branches:
      - master

env:
  WORKING_DIRECTORY: './src/Website/'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: yarn install, build, and test
      run: |
        #npm install
        yarn install
        yarn build 
        #yarn test
      working-directory: ${{ env.WORKING_DIRECTORY }}
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: application
        path: ${{ env.WORKING_DIRECTORY }}

  security:
    runs-on: windows-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: application
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  deploy:
    runs-on: windows-latest
    needs: security
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: application
    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'regionelombardia-web'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d58f1c4a6cc740649958da36bcd5b528 }}
        package: .